# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0002_auto_20170111_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
