# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0003_auto_20170113_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('email', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'verbose_name': 'Ruta Colectiv',
                'verbose_name_plural': 'Ruta Colectiv',
            },
        ),
    ]
