# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_route_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Emails', 'verbose_name_plural': 'Emails'},
        ),
    ]
